### ISSUE TITLE
Feature: report this website

### ISSUE THREAD

**Issue by zerodistraction** [kaishin/Nope#6]
It would be helpful to users if the extension had a "report website" option exposed in the UI. That way the user could report a problematic website. Optionally, you could ask the user to submit a short description of the problem.

**Comment by kaishin** [comment]
Since there is no backend (by design), I wonder where this data would be sent. One thing I can think of now is making that a new GitHub issue link and auto-fill the site's URL using this format `https://github.com/kaishin/Nope/issues/new?title=Issue20%with%20somesite.com&body=description`

This would require users to have GitHub accounts but I guess it's a good compromise to make to keep things simple.

**Comment by zerodistraction** [comment]
Yes, that's a fine compromise. I'd much rather have a direct link from the UI that auto fills the URL of the site I tried to report.

**Comment by kaishin** [comment]
<img width="247" alt="screenshot-2016-01-25-1" src="https://cloud.githubusercontent.com/assets/519433/12567914/f95d8f6e-c3b9-11e5-8bba-1925bb37470d.png">
